name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS Elastic Beanstalk
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login -u AWS --password-stdin ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image to AWS Elastic Beanstalk
        run: |
          docker build -t rpuk-seekers-website .
          docker tag rpuk-seekers-website:latest <aws-account-id>.dkr.ecr.<region>.amazonaws.com/rpuk-seekers-website:latest
          docker push <aws-account-id>.dkr.ecr.<region>.amazonaws.com/rpuk-seekers-website:latest

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
